-- 0094_profile_access_role_taxonomy.sql
-- Purpose: split user creation roles into Profile Type roles and Access Type bundle roles.

BEGIN;

INSERT INTO eip_authz.surface(code, label, sort_order) VALUES
  ('ADMIN','Admin',10),
  ('ERP','ERP',20),
  ('PARTNER','Partner Portal',30),
  ('ECOM','E-Commerce',40)
ON CONFLICT (code) DO NOTHING;

WITH role_defs(code, label, surface_code, is_system) AS (
  VALUES
    ('ADMIN_SUPER', 'Super Admin', 'ADMIN', true),
    ('ADMIN_EXEC', 'Executive Admin', 'ADMIN', true),
    ('ADMIN_ASSOC', 'Associate Admin', 'ADMIN', true),
    ('ECOM_ADMIN', 'ECOM Admin', 'ERP', true),
    ('ECOM_USER', 'ECOM User', 'ECOM', true),
    ('ERP_USER', 'ERP User', 'ERP', true),
    ('PARTNER_USER', 'Partner User', 'PARTNER', true),
    ('CRM_ADMIN', 'CRM Admin', 'ERP', true),
    ('CRM_USER', 'CRM User', 'ERP', true),
    ('ACCESS_UNIVERSAL', 'Universal Access', 'ERP', false),
    ('ACCESS_ECOM_FULL', 'Ecommerce Full Access', 'ERP', false),
    ('ACCESS_ECOM_CATALOG', 'Product & Content Studio', 'ERP', false),
    ('ACCESS_ECOM_ORDERS', 'Orders & Payments', 'ERP', false),
    ('ACCESS_CRM_FULL', 'CRM Full Access', 'ERP', false),
    ('ACCESS_READ_ONLY', 'Read Only', 'ERP', false)
)
INSERT INTO eip_authz.role(tenant_id, code, label, surface_code, is_system, is_active)
SELECT t.id, r.code, r.label, r.surface_code, r.is_system, true
FROM eip_core.tenant t
CROSS JOIN role_defs r
ON CONFLICT (tenant_id, code) DO NOTHING;

WITH bundles(role_code, permission_code) AS (
  VALUES
    ('ADMIN_SUPER', 'auth.device.read'),
    ('ADMIN_SUPER', 'auth.device.trust'),
    ('ADMIN_SUPER', 'auth.device.revoke'),
    ('ADMIN_SUPER', 'auth.password.write'),
    ('ADMIN_SUPER', 'authz.bootstrap.read'),
    ('ADMIN_SUPER', 'core.home.read'),
    ('ADMIN_SUPER', 'core.agent.read'),
    ('ADMIN_SUPER', 'core.agent.write'),
    ('ADMIN_SUPER', 'core.material.read'),
    ('ADMIN_SUPER', 'core.material.write'),
    ('ADMIN_SUPER', 'core.task.read'),
    ('ADMIN_SUPER', 'core.task.write'),
    ('ADMIN_SUPER', 'core.process.read'),
    ('ADMIN_SUPER', 'core.process.write'),
    ('ADMIN_SUPER', 'PROCESS_DEF_READ'),
    ('ADMIN_SUPER', 'PROCESS_DEF_WRITE'),
    ('ADMIN_SUPER', 'PROCESS_INSTANCE_READ'),
    ('ADMIN_SUPER', 'PROCESS_INSTANCE_WRITE'),
    ('ADMIN_SUPER', 'CRM_AGENT_READ'),
    ('ADMIN_SUPER', 'CRM_AGENT_WRITE'),
    ('ADMIN_SUPER', 'CRM_INTERACTION_READ'),
    ('ADMIN_SUPER', 'CRM_INTERACTION_WRITE'),
    ('ADMIN_SUPER', 'CRM_CASE_READ'),
    ('ADMIN_SUPER', 'CRM_CASE_WRITE'),
    ('ADMIN_SUPER', 'CRM_OPPORTUNITY_READ'),
    ('ADMIN_SUPER', 'CRM_OPPORTUNITY_WRITE'),
    ('ADMIN_SUPER', 'CRM_TASK_READ'),
    ('ADMIN_SUPER', 'CRM_TASK_WRITE'),
    ('ADMIN_SUPER', 'CRM_DASHBOARD_READ'),
    ('ADMIN_SUPER', 'CRM_PROCESS_DEF_READ'),
    ('ADMIN_SUPER', 'CRM_PROCESS_DEF_WRITE'),
    ('ADMIN_SUPER', 'ECOM_PRODUCT_READ'),
    ('ADMIN_SUPER', 'ECOM_PRODUCT_WRITE'),
    ('ADMIN_SUPER', 'ECOM_REVIEW_READ'),
    ('ADMIN_SUPER', 'ECOM_REVIEW_MODERATE'),
    ('ADMIN_SUPER', 'ECOM_ORDER_READ'),
    ('ADMIN_SUPER', 'ECOM_ORDER_WRITE'),
    ('ADMIN_SUPER', 'ECOM_RETURN_READ'),
    ('ADMIN_SUPER', 'ECOM_RETURN_WRITE'),
    ('ADMIN_SUPER', 'ECOM_REFUND_READ'),
    ('ADMIN_SUPER', 'ECOM_REFUND_WRITE'),
    ('ADMIN_SUPER', 'ECOM_SETTINGS_WRITE'),
    ('ADMIN_SUPER', 'tenant.admin_access.read'),
    ('ADMIN_SUPER', 'tenant.admin_access.write'),
    ('ADMIN_SUPER', 'tenant.connection.read'),
    ('ADMIN_SUPER', 'tenant.connection.write'),
    ('ADMIN_SUPER', 'tenant.connection.api_key'),
    ('ADMIN_SUPER', 'tenant.connection.template'),
    ('ADMIN_SUPER', 'tenant.connection.log'),
    ('ADMIN_SUPER', 'privacy.data.export'),
    ('ADMIN_SUPER', 'privacy.erasure.execute'),
    ('ADMIN_SUPER', 'privacy.consent.manage'),
    ('ADMIN_SUPER', 'privacy.audit.view'),
    ('ACCESS_UNIVERSAL', 'auth.device.read'),
    ('ACCESS_UNIVERSAL', 'auth.device.trust'),
    ('ACCESS_UNIVERSAL', 'auth.device.revoke'),
    ('ACCESS_UNIVERSAL', 'auth.password.write'),
    ('ACCESS_UNIVERSAL', 'authz.bootstrap.read'),
    ('ACCESS_UNIVERSAL', 'core.home.read'),
    ('ACCESS_UNIVERSAL', 'core.agent.read'),
    ('ACCESS_UNIVERSAL', 'core.agent.write'),
    ('ACCESS_UNIVERSAL', 'core.material.read'),
    ('ACCESS_UNIVERSAL', 'core.material.write'),
    ('ACCESS_UNIVERSAL', 'core.task.read'),
    ('ACCESS_UNIVERSAL', 'core.task.write'),
    ('ACCESS_UNIVERSAL', 'core.process.read'),
    ('ACCESS_UNIVERSAL', 'core.process.write'),
    ('ACCESS_UNIVERSAL', 'PROCESS_DEF_READ'),
    ('ACCESS_UNIVERSAL', 'PROCESS_DEF_WRITE'),
    ('ACCESS_UNIVERSAL', 'PROCESS_INSTANCE_READ'),
    ('ACCESS_UNIVERSAL', 'PROCESS_INSTANCE_WRITE'),
    ('ACCESS_UNIVERSAL', 'CRM_AGENT_READ'),
    ('ACCESS_UNIVERSAL', 'CRM_AGENT_WRITE'),
    ('ACCESS_UNIVERSAL', 'CRM_INTERACTION_READ'),
    ('ACCESS_UNIVERSAL', 'CRM_INTERACTION_WRITE'),
    ('ACCESS_UNIVERSAL', 'CRM_CASE_READ'),
    ('ACCESS_UNIVERSAL', 'CRM_CASE_WRITE'),
    ('ACCESS_UNIVERSAL', 'CRM_OPPORTUNITY_READ'),
    ('ACCESS_UNIVERSAL', 'CRM_OPPORTUNITY_WRITE'),
    ('ACCESS_UNIVERSAL', 'CRM_TASK_READ'),
    ('ACCESS_UNIVERSAL', 'CRM_TASK_WRITE'),
    ('ACCESS_UNIVERSAL', 'CRM_DASHBOARD_READ'),
    ('ACCESS_UNIVERSAL', 'CRM_PROCESS_DEF_READ'),
    ('ACCESS_UNIVERSAL', 'CRM_PROCESS_DEF_WRITE'),
    ('ACCESS_UNIVERSAL', 'ECOM_PRODUCT_READ'),
    ('ACCESS_UNIVERSAL', 'ECOM_PRODUCT_WRITE'),
    ('ACCESS_UNIVERSAL', 'ECOM_REVIEW_READ'),
    ('ACCESS_UNIVERSAL', 'ECOM_REVIEW_MODERATE'),
    ('ACCESS_UNIVERSAL', 'ECOM_ORDER_READ'),
    ('ACCESS_UNIVERSAL', 'ECOM_ORDER_WRITE'),
    ('ACCESS_UNIVERSAL', 'ECOM_RETURN_READ'),
    ('ACCESS_UNIVERSAL', 'ECOM_RETURN_WRITE'),
    ('ACCESS_UNIVERSAL', 'ECOM_REFUND_READ'),
    ('ACCESS_UNIVERSAL', 'ECOM_REFUND_WRITE'),
    ('ACCESS_UNIVERSAL', 'ECOM_SETTINGS_WRITE'),
    ('ACCESS_UNIVERSAL', 'tenant.admin_access.read'),
    ('ACCESS_UNIVERSAL', 'tenant.admin_access.write'),
    ('ACCESS_UNIVERSAL', 'tenant.connection.read'),
    ('ACCESS_UNIVERSAL', 'tenant.connection.write'),
    ('ACCESS_UNIVERSAL', 'tenant.connection.api_key'),
    ('ACCESS_UNIVERSAL', 'tenant.connection.template'),
    ('ACCESS_UNIVERSAL', 'tenant.connection.log'),
    ('ACCESS_UNIVERSAL', 'privacy.data.export'),
    ('ACCESS_UNIVERSAL', 'privacy.erasure.execute'),
    ('ACCESS_UNIVERSAL', 'privacy.consent.manage'),
    ('ACCESS_UNIVERSAL', 'privacy.audit.view'),
    ('ACCESS_ECOM_FULL', 'authz.bootstrap.read'),
    ('ACCESS_ECOM_FULL', 'core.home.read'),
    ('ACCESS_ECOM_FULL', 'ECOM_PRODUCT_READ'),
    ('ACCESS_ECOM_FULL', 'ECOM_PRODUCT_WRITE'),
    ('ACCESS_ECOM_FULL', 'ECOM_REVIEW_READ'),
    ('ACCESS_ECOM_FULL', 'ECOM_REVIEW_MODERATE'),
    ('ACCESS_ECOM_FULL', 'ECOM_ORDER_READ'),
    ('ACCESS_ECOM_FULL', 'ECOM_ORDER_WRITE'),
    ('ACCESS_ECOM_FULL', 'ECOM_RETURN_READ'),
    ('ACCESS_ECOM_FULL', 'ECOM_RETURN_WRITE'),
    ('ACCESS_ECOM_FULL', 'ECOM_REFUND_READ'),
    ('ACCESS_ECOM_FULL', 'ECOM_REFUND_WRITE'),
    ('ACCESS_ECOM_FULL', 'ECOM_SETTINGS_WRITE'),
    ('ACCESS_ECOM_CATALOG', 'authz.bootstrap.read'),
    ('ACCESS_ECOM_CATALOG', 'core.home.read'),
    ('ACCESS_ECOM_CATALOG', 'ECOM_PRODUCT_READ'),
    ('ACCESS_ECOM_CATALOG', 'ECOM_PRODUCT_WRITE'),
    ('ACCESS_ECOM_CATALOG', 'ECOM_REVIEW_READ'),
    ('ACCESS_ECOM_CATALOG', 'ECOM_REVIEW_MODERATE'),
    ('ACCESS_ECOM_ORDERS', 'authz.bootstrap.read'),
    ('ACCESS_ECOM_ORDERS', 'core.home.read'),
    ('ACCESS_ECOM_ORDERS', 'ECOM_ORDER_READ'),
    ('ACCESS_ECOM_ORDERS', 'ECOM_ORDER_WRITE'),
    ('ACCESS_ECOM_ORDERS', 'ECOM_RETURN_READ'),
    ('ACCESS_ECOM_ORDERS', 'ECOM_RETURN_WRITE'),
    ('ACCESS_ECOM_ORDERS', 'ECOM_REFUND_READ'),
    ('ACCESS_ECOM_ORDERS', 'ECOM_REFUND_WRITE'),
    ('ACCESS_CRM_FULL', 'authz.bootstrap.read'),
    ('ACCESS_CRM_FULL', 'core.home.read'),
    ('ACCESS_CRM_FULL', 'CRM_AGENT_READ'),
    ('ACCESS_CRM_FULL', 'CRM_AGENT_WRITE'),
    ('ACCESS_CRM_FULL', 'CRM_INTERACTION_READ'),
    ('ACCESS_CRM_FULL', 'CRM_INTERACTION_WRITE'),
    ('ACCESS_CRM_FULL', 'CRM_CASE_READ'),
    ('ACCESS_CRM_FULL', 'CRM_CASE_WRITE'),
    ('ACCESS_CRM_FULL', 'CRM_OPPORTUNITY_READ'),
    ('ACCESS_CRM_FULL', 'CRM_OPPORTUNITY_WRITE'),
    ('ACCESS_CRM_FULL', 'CRM_TASK_READ'),
    ('ACCESS_CRM_FULL', 'CRM_TASK_WRITE'),
    ('ACCESS_CRM_FULL', 'CRM_DASHBOARD_READ'),
    ('ACCESS_CRM_FULL', 'PROCESS_DEF_READ'),
    ('ACCESS_CRM_FULL', 'PROCESS_DEF_WRITE'),
    ('ACCESS_CRM_FULL', 'PROCESS_INSTANCE_READ'),
    ('ACCESS_CRM_FULL', 'PROCESS_INSTANCE_WRITE'),
    ('ACCESS_READ_ONLY', 'authz.bootstrap.read'),
    ('ACCESS_READ_ONLY', 'core.home.read'),
    ('ACCESS_READ_ONLY', 'core.agent.read'),
    ('ACCESS_READ_ONLY', 'core.material.read'),
    ('ACCESS_READ_ONLY', 'core.task.read'),
    ('ACCESS_READ_ONLY', 'core.process.read'),
    ('ACCESS_READ_ONLY', 'ECOM_PRODUCT_READ'),
    ('ACCESS_READ_ONLY', 'ECOM_REVIEW_READ'),
    ('ACCESS_READ_ONLY', 'ECOM_ORDER_READ'),
    ('ACCESS_READ_ONLY', 'ECOM_RETURN_READ'),
    ('ACCESS_READ_ONLY', 'ECOM_REFUND_READ'),
    ('ACCESS_READ_ONLY', 'CRM_AGENT_READ'),
    ('ACCESS_READ_ONLY', 'CRM_INTERACTION_READ'),
    ('ACCESS_READ_ONLY', 'CRM_CASE_READ'),
    ('ACCESS_READ_ONLY', 'CRM_OPPORTUNITY_READ'),
    ('ACCESS_READ_ONLY', 'CRM_TASK_READ'),
    ('ACCESS_READ_ONLY', 'CRM_DASHBOARD_READ'),
    ('ACCESS_READ_ONLY', 'PROCESS_DEF_READ'),
    ('ACCESS_READ_ONLY', 'PROCESS_INSTANCE_READ')
)
INSERT INTO eip_authz.role_permission(role_id, permission_code)
SELECT r.id, p.code
FROM eip_authz.role r
JOIN bundles b ON b.role_code = r.code
JOIN eip_authz.permission p ON p.code = b.permission_code
ON CONFLICT DO NOTHING;

COMMIT;
