export const dashboardSurface = {
  id: "dashboard",
  title: "User Dashboard",
  tree: {
    id: "user-shell",
    type: "UserShell",
    props: {
      brand: "EIP Core",
      nav: ["Dashboard", "Product Studio", "Content Studio", "Orders & Payments", "Inventory", "Procurement", "Entities", "Policies & Conditions", "Tasks", "Reports", "Security", "Settings"],
      menu: [
        { code: "dashboard", label: "Dashboard", icon: "LayoutGrid" },
        { code: "catalog", label: "Product Studio", icon: "Package" },
        { code: "content", label: "Content Studio", icon: "LayoutTemplate" },
        { code: "commerce", label: "Orders & Payments", icon: "CreditCard" },
        { code: "inventory", label: "Inventory", icon: "Package", module: "inventory" },
        { code: "procurement", label: "Procurement", icon: "ShoppingCart", module: "procurement" },
        { code: "entities", label: "Entities", icon: "Users", module: "entity-management" },
        { code: "policies", label: "Policies & Conditions", icon: "FileClock" },
        { code: "crm", label: "CRM", icon: "Users", module: "crm" },
        { code: "tasks", label: "Tasks", icon: "Activity" },
        { code: "reports", label: "Reports", icon: "BarChart3" },
        { code: "security", label: "Security", icon: "Shield" },
        { code: "settings", label: "Settings", icon: "Settings" },
      ],
      helper: "Workspace overview, catalog operations, and tenant tasks.",
    },
    children: [
      {
        id: "user-dashboard-panel",
        type: "UserPanel",
        props: { tab: "dashboard" },
        children: [
        {
          id: "user-dashboard",
          type: "UserDashboardPanel",
          props: {
            endpoint: "/api/eip/user/dashboard/command-center",
            title: "Run the business, not the system",
            subtitle: "Live business signals, urgent topics, and actionables from existing task and module data.",
            tabs: [
              { code: "command", label: "Command Center" },
              { code: "analytics", label: "Analytics" },
            ],
            widgets: [
              { code: "open_work", label: "Open work" },
              { code: "high_urgency", label: "High urgency" },
              { code: "due_today", label: "Due today" },
              { code: "active_modules", label: "Active modules" },
              { code: "recent_reports", label: "Recent reports" },
            ],
            labels: {
              refresh: "Refresh",
              businessStats: "Business statistics",
              businessStatsHint: "Live task, module, report, and operational signals",
              openDetail: "Open detail",
              burningTopics: "Burning topics",
              burningHint: "Top urgent items only. User pins 2-3 categories from the Task Browser.",
              burningEmpty: "No urgent item is waiting in the pinned categories.",
              taskBrowser: "Task Browser",
              taskBrowserHint: "All user actionables - categories are metadata-driven",
              taskSearch: "Search actionables...",
              signalSearch: "Search signal, customer, order, material...",
              actionables: "Actionables",
              controls: "Filters, delegation rules and category pinning",
              analytics: "Signal analytics",
              workload: "Workload balance",
              delegate: "Delegate",
              assign: "Assign",
              cancel: "Cancel",
              confirm: "Confirm",
              noTasks: "No open tasks in this category.",
              search: "Search tasks",
              urgency: "Urgency",
              sort: "Sort",
              pinned: "Pinned",
            },
            categoryPresentation: {
              crm: { label: "Customer queries", badge: "CRM / INTAKE", tone: "blue" },
              commerce: { label: "Orders to deliver", badge: "ORDER FLOW", tone: "red" },
              inventory: { label: "Stock risks", badge: "INVENTORY", tone: "gold" },
              procurement: { label: "RFQ / Suppliers", badge: "PROCUREMENT", tone: "violet" },
              content: { label: "Content & catalog", badge: "STORE", tone: "green" },
              reports: { label: "Reports & review", badge: "REPORTING", tone: "slate" },
              general: { label: "General work", badge: "TASKS", tone: "slate" },
            },
            taskBrowser: {
              defaultOpen: "crm",
              urgencyFilters: ["all", "critical", "high", "medium", "normal"],
              dueDateFilters: ["all", "overdue", "today", "tomorrow", "future", "unscheduled"],
              assignmentFilters: ["all", "my_tasks", "delegated", "unassigned"],
              sortOptions: ["urgency", "due_date", "category", "created_date"],
            },
            theme: {
              variant: "eip_v1",
              density: "comfortable",
            },
          },
        },
      ],
    },
    {
      id: "user-catalog-panel",
      type: "UserPanel",
      props: { tab: "catalog" },
      children: [
        {
          id: "catalog-workspace",
          type: "EcomProductWorkspace",
          props: {
            productStudio: {
              tabs: [
                { id: "studio", label: "Studio" },
                { id: "focus", label: "Focus" },
              ],
              focusRules: [
                { code: "rejected", label: "Rejected products", action: "Review rejection" },
                { code: "pending_publish", label: "Pending publish", action: "Open publish task" },
                { code: "missing_trade_conditions", label: "Missing trade conditions", action: "Complete trade terms" },
                { code: "missing_category", label: "Missing category/type", action: "Complete setup" },
                { code: "inventory_setup", label: "Physical inventory setup", action: "Complete initial inventory" },
              ],
              tradeConditions: {
                title: "Trade conditions",
                subtitle: "Commercial rules, pricing terms, supplier/customer terms, validity, and renewal tasks.",
              },
            },
          },
        },
      ],
    },
    {
      id: "user-content-panel",
      type: "UserPanel",
      props: { tab: "content" },
      children: [
        {
          id: "content-workspace",
          type: "EcomProductWorkspace",
          props: {
            mode: "content-studio",
            storefrontMapping: {
              title: "Storefront mapping",
              scanButtonLabel: "Scan",
              scanningLabel: "Scanning...",
              connectionLabel: "Scan connection",
              modeLabel: "Scan mode",
              connectionLoadingLabel: "Loading connections...",
              connectionEmptyLabel: "No connected frontend",
              structureLoadingLabel: "Loading structure...",
              structureEmptyLabel: "No structure map yet. Run scan.",
              zoneMappingLabel: "Zone mapping",
              viewMapLabel: "View map",
              scanModes: [
                { value: "auto", label: "Auto scan" },
                { value: "rendered", label: "Rendered DOM scan" },
                { value: "generic", label: "Static generic scan" },
                { value: "tagged", label: "Tagged fallback scan" },
              ],
              rendererOptions: [
                "hero_slider",
                "product_carousel",
                "product_grid",
                "editorial_card_grid",
                "rich_text_block",
                "cta_block",
                "newsletter_form",
                "media_gallery",
                "testimonial_grid",
                "feature_block",
              ],
              productSourceModes: [
                { value: "", label: "Editorial content" },
                { value: "manual_products", label: "Manual product codes" },
                { value: "product_tag", label: "Product tag" },
                { value: "collection_or_drop", label: "Collection or drop" },
                { value: "hybrid_tag_overrides", label: "Tag with manual overrides" },
              ],
              slotPresets: [
                { slot: "home.hero", title: "Home hero", page: "home", mode: "hero", description: "Main landing slider for the storefront home page." },
                { slot: "pages.hero", title: "Pages hero", page: "pages", mode: "hero", description: "Hero band for the Pages tab." },
                { slot: "pages.cards", title: "Pages cards", page: "pages", mode: "cards", description: "Card content shown inside Pages tab." },
                { slot: "sizes.hero", title: "Sizes hero", page: "sizes", mode: "hero", description: "Intro copy and hero art for Sizes tab." },
                { slot: "blog.hero", title: "Blog hero", page: "blog", mode: "hero", description: "Hero copy for the Blog tab." },
                { slot: "line.hero", title: "Line hero", page: "line", mode: "hero", description: "Collection planning hero section." },
                { slot: "line.cards", title: "Line cards", page: "line", mode: "cards", description: "Capsule cards for Line tab." },
                { slot: "learning.hero", title: "Learning hero", page: "learning", mode: "hero", description: "Learning tab hero section." },
                { slot: "learning.cards", title: "Learning cards", page: "learning", mode: "cards", description: "Training track/session cards." },
                { slot: "collab.hero", title: "Collab hero", page: "collab", mode: "hero", description: "Collab shop hero section." },
                { slot: "collab.cards", title: "Collab cards", page: "collab", mode: "cards", description: "Program cards for Collab tab." },
              ],
              requiredFieldsByRenderer: {
                hero_slider: ["slides"],
                product_carousel: ["source_mode"],
                product_grid: ["source_mode"],
                editorial_card_grid: ["slides"],
                rich_text_block: ["slides"],
                cta_block: ["slides"],
                newsletter_form: ["slides"],
              },
              modal: {
                eyebrow: "Storefront structure",
                title: "Detected zone mapping",
                subtitle: "Review inferred website zones, approve slots, then create governed content.",
                closeLabel: "Close",
              },
              actions: {
                approve: "Approve",
                edit: "Edit",
                ignore: "Ignore",
                reset: "Reset",
                openContent: "Open content",
                createContent: "Create content",
              },
            },
          },
        },
      ],
    },
    {
      id: "user-commerce-panel",
      type: "UserPanel",
      props: { tab: "commerce" },
      children: [
        {
          id: "commerce-lifecycle-panel",
          type: "EcomOrderManagementPanel",
          props: {
            layout: {
              header: {
                eyebrow: "Commerce",
                title: "Orders & payments",
                subtitle:
                  "Track sales orders, returns, and refunds flowing through the core process engine.",
              },
              tabs: [
                { id: "orders", label: "Orders", icon: "ClipboardList" },
                { id: "returns", label: "Returns", icon: "RotateCcw" },
                { id: "refunds", label: "Refunds", icon: "DollarSign" },
                { id: "payments", label: "Payments", icon: "CreditCard" },
              ],
              list: {
                title: "Queue",
                searchPlaceholder: "Search orders, buyers, items...",
                perPageLabel: "Per page",
                perPageOptions: [12, 25, 50],
                refreshLabel: "Refresh",
                empty: "Nothing here yet.",
                emptyFiltered: "No orders match the current search.",
                pageLabel: "Page",
                pageOfLabel: "of",
                prevLabel: "Prev",
                nextLabel: "Next",
                ellipsisLabel: "...",
                codeFallback: "ORDER",
                itemFallback: "Order",
                buyerFallback: "Buyer",
                stageFallback: "new",
                orderLabel: "Order",
                untitledFallback: "Untitled",
              },
              detail: {
                title: "Order details",
                orderNumberLabel: "Order no.",
                orderCodeLabel: "Code",
                untitledOrder: "Sales order",
                untitledItem: "Order item",
                invoiceLabel: "Invoice",
                contactLabel: "Contact us",
                statusLabel: "Order status",
                trackTitle: "Track order",
                paymentTitle: "Payment details",
                paymentMethodLabel: "Payment method",
                paymentPendingLabel: "Pending",
                billingTitle: "Billing information",
                summaryTitle: "Order summary",
                summaryLabels: {
                  subtotal: "Product price",
                  shipping: "Delivery",
                  tax: "Taxes",
                  total: "Total",
                },
                metaLabels: {
                  created: "Created",
                  channel: "Channel",
                  buyer: "Buyer",
                  buyerEmail: "Buyer email",
                  jurisdiction: "Jurisdiction",
                  currency: "Currency",
                },
                trackLabels: {
                  received: "Order received",
                  confirmed: "Order confirmed",
                  packed: "Order packed",
                  shipped: "Order shipped",
                  delivered: "Order delivered",
                },
                trackIcons: {
                  received: "Bell",
                  confirmed: "FileText",
                  packed: "Package",
                  shipped: "Truck",
                  delivered: "Check",
                },
                trackIconFallback: "CircleDot",
                trackSteps: [
                  {
                    key: "received",
                    label: "Order received",
                    icon: "Bell",
                    match: ["received", "created", "intake"],
                  },
                  {
                    key: "confirmed",
                    label: "Order confirmed",
                    icon: "FileText",
                    match: ["confirmed", "order_confirm", "order_approve"],
                  },
                  {
                    key: "packed",
                    label: "Order packed",
                    icon: "Package",
                    match: ["packed", "order_pack"],
                  },
                  {
                    key: "shipped",
                    label: "Order transmitted to courier",
                    icon: "Truck",
                    match: ["shipped", "order_ship", "order_transmit"],
                  },
                  {
                    key: "delivered",
                    label: "Order delivered",
                    icon: "Check",
                    match: ["delivered", "order_deliver", "order_fulfill", "fulfilled"],
                  },
                ],
                fulfillmentTitle: "Fulfillment",
                lineItemsTitle: "Line items",
                lineItemLabel: "Item",
                lineItemsQtyLabel: "Qty",
                lineItemsAtLabel: "@",
                lineItemsEmpty: "No order lines recorded.",
                customerRequestsTitle: "Customer requests",
                returnReasonLabel: "Return reason",
                requestReturnLabel: "Request return",
                refundLabel: "Refund",
                refundReasonPlaceholder: "Reason",
                refundAmountPlaceholder: "Amount (leave blank for full refund)",
                requestRefundLabel: "Request refund",
                returnsTitle: "Returns",
                returnsEmpty: "No returns yet.",
                refundsTitle: "Refunds",
                refundsEmpty: "No refunds yet.",
                paymentsTitle: "Payments",
                paymentsEmpty: "No payments yet.",
                returnTitle: "Return",
                refundTitle: "Refund",
                orderLabel: "Order",
                amountLabel: "Amount",
                actionLabels: {
                  order: {
                    ORDER_CONFIRM: "Confirm",
                    ORDER_PACK: "Pack",
                    ORDER_SHIP: "Ship",
                    ORDER_FULFILL: "Fulfill",
                    ORDER_DELIVER: "Deliver",
                    ORDER_CANCEL: "Cancel",
                  },
                  return: {
                    RETURN_APPROVE: "Approve",
                    RETURN_REJECT: "Reject",
                    RETURN_RECEIVE: "Receive",
                  },
                  refund: {
                    REFUND_APPROVE: "Approve",
                    REFUND_REJECT: "Reject",
                    REFUND_ISSUE: "Issue",
                  },
                },
                messages: {
                  loadingOrder: "Loading order...",
                  loadingReturn: "Loading return...",
                  loadingRefund: "Loading refund...",
                  selectOrder: "Select an order to see details.",
                  selectReturn: "Select a return to see details.",
                  selectRefund: "Select a refund to see details.",
                  orderUpdated: "Order updated.",
                  returnRequestCreated: "Return request created.",
                  refundRequestCreated: "Refund request created.",
                },
                skeleton: {
                  enabled: true,
                  timePlaceholder: "-",
                  lineItemsCount: 2,
                },
              },
            },
          },
        },
      ],
    },
    {
      id: "user-inventory-panel",
      type: "UserPanel",
      props: { tab: "inventory" },
      children: [
        {
          id: "inventory-workspace",
          type: "InventoryWorkspace",
          props: {
            module: "inventory",
            title: "Inventory",
            subtitle: "Stock signal queue, policy-backed recommendation, procurement handoff, and timeline.",
            endpoints: {
              overview: "/api/eip/inventory/overview",
              materials: "/api/eip/inventory/materials",
              suggestions: "/api/eip/inventory/reorder-suggestions",
              workbench: "/api/eip/inventory/reorder-suggestions",
            },
            tabs: [
              { id: "queue", label: "Stock Signals Queue" },
              { id: "workbench", label: "Inventory Signal Workbench" },
              { id: "actions", label: "Action Rail" },
              { id: "tools", label: "Material Policy Tools" },
            ],
            actions: {
              refresh: "Refresh",
              runReorder: "Run low-stock scan",
              adjust: "Adjust stock",
              policy: "Set reorder policy",
              movements: "View movements",
              createSuggestion: "Create reorder suggestion",
              approve: "Approve",
              ignore: "Ignore",
              createTask: "Create task",
              openProcurement: "Open in Procurement",
            },
          },
        },
      ],
    },
    {
      id: "user-crm-panel",
      type: "UserPanel",
      props: { tab: "crm" },
      children: [
        {
          id: "crm-workspace",
          type: "CrmWorkspace",
          props: {
            module: "crm",
            title: "CRM",
            subtitle: "Customers, leads, opportunities, cases, interactions, and follow-ups.",
            tabs: [
              { id: "overview", label: "Overview", kind: "overview" },
              { id: "intake", label: "Intake Inbox", kind: "intake", endpoint: "/api/eip/crm/intake", permission: "CRM_INTAKE_READ", capability: "intake" },
              { id: "mailbox", label: "Mailbox", kind: "mailbox", endpoint: "/api/eip/crm/mailbox/messages", permission: "CRM_MAILBOX_READ", capability: "mailbox" },
              { id: "mailbox_replies", label: "Reply Drafts", kind: "mailbox_reply", endpoint: "/api/eip/crm/mailbox/replies", permission: "CRM_MAILBOX_READ", capability: "mailbox" },
              { id: "leads", label: "Leads", kind: "service_object", endpoint: "/api/eip/crm/leads", permission: "CRM_LEAD_READ" },
              { id: "agents", label: "Customers", kind: "agent", endpoint: "/api/eip/crm/agents", permission: "CRM_AGENT_READ" },
              { id: "opportunities", label: "Opportunities", kind: "service_object", endpoint: "/api/eip/crm/opportunities", permission: "CRM_OPPORTUNITY_READ" },
              { id: "cases", label: "Cases", kind: "service_object", endpoint: "/api/eip/crm/cases", permission: "CRM_CASE_READ" },
              { id: "interactions", label: "Interactions", kind: "service_object", endpoint: "/api/eip/crm/interactions", permission: "CRM_INTERACTION_READ" },
              { id: "tasks", label: "Follow-ups", kind: "task", endpoint: "/api/eip/crm/tasks", permission: "CRM_TASK_READ" },
              { id: "intelligence", label: "Intelligence", kind: "intelligence", endpoint: "/api/eip/crm/intelligence/overview", permission: "CRM_INTELLIGENCE_READ", capability: "intelligence" },
              { id: "segments", label: "Segments", kind: "agent", endpoint: "/api/eip/crm/segments", permission: "CRM_SEGMENT_READ", capability: "segments" },
              { id: "campaigns", label: "Campaigns", kind: "service_object", endpoint: "/api/eip/crm/campaigns", permission: "CRM_CAMPAIGN_READ", capability: "campaigns" },
              { id: "signals", label: "Signals", kind: "info_record", endpoint: "/api/eip/crm/signals", permission: "CRM_SIGNAL_READ", capability: "signals" },
              { id: "connectors", label: "Connectors", kind: "connector", endpoint: "/api/eip/crm/intelligence/connectors", permission: "CRM_CONNECTOR_READ", capability: "connectors" },
            ],
          },
        },
      ],
    },
    {
      id: "user-procurement-panel",
      type: "UserPanel",
      props: { tab: "procurement" },
      children: [
        {
          id: "procurement-workspace",
          type: "ProcurementWorkspace",
          props: {
            module: "procurement",
            title: "Purchase Need Workbench",
            subtitle: "Review what needs buying, supplier options, buying route, offers, and the next owner action.",
            endpoints: {
              overview: "/api/eip/procurement/overview",
              workbench: "/api/eip/procurement/purchase-needs",
              lookup: "/api/eip/procurement/lookup",
              supplierLinks: "/api/eip/procurement/supplier-links",
              requisitions: "/api/eip/procurement/requisitions",
              rfqs: "/api/eip/procurement/rfqs",
              cashPurchases: "/api/eip/procurement/cash-purchases",
            },
            tabs: [
              { id: "workbench", label: "Purchase Need Workbench" },
              { id: "supplier-policy", label: "Supplier Policy" },
              { id: "history", label: "History" },
            ],
            actions: {
              refresh: "Refresh",
              createRequisition: "Create requisition",
              approve: "Approve",
              ignore: "Ignore",
              createRfq: "Request quotes",
              addQuote: "Add supplier offer",
              compareQuotes: "Compare offers",
              approveQuote: "Approve recommended offer",
              saveSupplierLink: "Save supplier link",
              recordCashPurchase: "Record cash purchase",
            },
          },
        },
      ],
    },
    {
      id: "user-policies-panel",
      type: "UserPanel",
      props: { tab: "policies" },
      children: [
        {
          id: "policies-conditions-workspace",
          type: "PoliciesConditionsWorkspace",
          props: {
            title: "Policies & Conditions",
            subtitle: "Read-only business rules that explain recommendations and approvals.",
            endpoints: {
              list: "/api/eip/policies-conditions",
              detail: "/api/eip/policies-conditions/:id",
              overview: "/api/eip/policies-conditions/overview",
              taxonomy: "/api/eip/policies-conditions/taxonomy",
            },
            tabs: [
              { id: "overview", label: "Overview" },
              { id: "library", label: "Policy Library" },
              { id: "needs_review", label: "Needs Review" },
            ],
            labels: {
              search: "Search policies...",
              refresh: "Refresh",
              readOnly: "Create/edit will be added in a later governed wave.",
              emptyTitle: "No policies or conditions yet",
              emptyMessage: "Create governed business rules before EIP can explain recommendations for this area.",
              detailTitle: "Condition detail",
              noSelection: "Select a policy or condition to inspect the read model.",
            },
            pageSizes: [12, 25, 50],
            domainOptions: [
              "COMMERCIAL",
              "FINANCIAL",
              "APPROVAL_FRAMEWORK",
              "INVENTORY",
              "FISCAL_TAX_TREATMENT",
              "MARKETPLACE",
              "LOGISTICS",
            ],
          },
        },
      ],
    },
    {
      id: "user-entities-panel",
      type: "UserPanel",
      props: { tab: "entities" },
      children: [
        {
          id: "entity-management-workspace",
          type: "EntityManagementWorkspace",
          props: {
            module: "entity-management",
            title: "Entity Management",
            subtitle: "Customers, suppliers, employees, partners, authorities, addresses, contacts, bank accounts, relationships, documents, policies, and activity.",
            endpoints: {
              list: "/api/eip/entities",
              detail: "/api/eip/entities/:id",
              options: "/api/eip/entities/governance/options",
            },
            tabs: [
              { id: "overview", label: "Overview" },
              { id: "addresses", label: "Addresses" },
              { id: "contacts", label: "Contacts" },
              { id: "bank_accounts", label: "Bank Accounts" },
              { id: "relationships", label: "Relationships" },
              { id: "documents", label: "Documents" },
              { id: "policies", label: "Policies" },
              { id: "activity", label: "Activity" },
            ],
            actions: {
              refresh: "Refresh",
              create: "Create entity",
              save: "Save",
              archive: "Archive",
              addAddress: "Add address",
              addContact: "Add contact",
              addBankAccount: "Add bank account",
              addRelationship: "Add relationship",
            },
          },
        },
      ],
    },
    {
      id: "user-tasks-panel",
      type: "UserPanel",
        props: { tab: "tasks" },
        children: [
          {
            id: "user-tasks",
            type: "UserTasksPanel",
            props: {
              title: "Tasks",
              subtitle: "Full task management, scheduling, delegation, and workload from real task engine records.",
              endpoint: "/api/eip/user/dashboard/command-center",
              defaultView: "my_tasks",
              views: [
                { code: "my_tasks", label: "My Tasks" },
                { code: "calendar", label: "Calendar" },
                { code: "delegated", label: "Delegated" },
                { code: "overdue", label: "Overdue" },
                { code: "workload", label: "Workload" },
              ],
            },
          },
        ],
      },
      {
        id: "user-reports-panel",
        type: "UserPanel",
        props: { tab: "reports" },
        children: [
          {
            id: "user-reports-placeholder",
            type: "UserPlaceholderPanel",
            props: {
              title: "Reports",
              subtitle: "Download activity reports and exports here.",
            },
          },
        ],
      },
      {
        id: "user-security-panel",
        type: "UserPanel",
        props: { tab: "security" },
        children: [
          {
            id: "user-security",
            type: "UserSecurityPanel",
          },
        ],
      },
      {
        id: "user-settings-panel",
        type: "UserPanel",
        props: { tab: "settings" },
        children: [
          {
            id: "tenant-admin-access",
            type: "TenantAdminAccessPanel",
          },
          {
            id: "commerce-payment-settings",
            type: "EcomCommerceSettingsPanel",
            props: {
              module: "ecom",
              capability: "payments",
              placement: "settings",
              layout: {
                eyebrow: "Settings",
                title: "Commerce / Payments",
                subtitle: "Tenant-local commerce preferences and payment readiness. Provider secrets stay in Admin Console > Connections.",
                paymentTitle: "Payment readiness & preferences",
                paymentSubtitle: "Enable storefront payment methods, choose business policy, and verify provider readiness without exposing secrets.",
                operationsPath: "Dashboard > Orders & Payments > Payments",
                connectionsPath: "Admin Console > Connections",
              },
            },
          },
        ],
      },
    ],
  },
};
