import fs from "node:fs";
import path from "node:path";
import https from "node:https";

const ROOT = path.resolve(process.cwd());
const OUT_PATH = path.join(
  ROOT,
  "services",
  "api",
  "db",
  "seed",
  "jurisdiction_iso_seed.sql"
);

const SOURCES = {
  countries:
    "https://datahub.io/core/country-codes/r/country-codes.csv",
  timezones: "https://data.iana.org/time-zones/tzdb/zone1970.tab",
};

function fetchText(url) {
  return new Promise((resolve, reject) => {
    https
      .get(url, (res) => {
        if (res.statusCode && res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          return resolve(fetchText(res.headers.location));
        }
        if (res.statusCode !== 200) {
          reject(new Error(`HTTP ${res.statusCode} for ${url}`));
          res.resume();
          return;
        }
        let data = "";
        res.setEncoding("utf8");
        res.on("data", (chunk) => {
          data += chunk;
        });
        res.on("end", () => resolve(data));
      })
      .on("error", reject);
  });
}

function parseCsvLine(line) {
  const out = [];
  let cur = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i += 1) {
    const ch = line[i];
    if (ch === "\"") {
      const next = line[i + 1];
      if (inQuotes && next === "\"") {
        cur += "\"";
        i += 1;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }
    if (ch === "," && !inQuotes) {
      out.push(cur);
      cur = "";
      continue;
    }
    cur += ch;
  }
  out.push(cur);
  return out;
}

function normalizeHeader(value) {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, " ")
    .replace(/_/g, " ");
}

function getField(row, keys) {
  for (const key of keys) {
    if (Object.prototype.hasOwnProperty.call(row, key)) {
      const value = row[key];
      if (value !== undefined && value !== null && String(value).trim() !== "") {
        return String(value).trim();
      }
    }
  }
  return "";
}

function padNumeric(value) {
  const raw = String(value || "").trim();
  if (!raw) return "";
  return raw.padStart(3, "0");
}

function sqlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function chunkArray(list, size) {
  const out = [];
  for (let i = 0; i < list.length; i += size) {
    out.push(list.slice(i, i + size));
  }
  return out;
}

function parseCountryCsv(text) {
  const lines = text.split(/\r?\n/).filter((line) => line.trim() !== "");
  if (!lines.length) return [];
  const rawHeaders = parseCsvLine(lines[0]);
  const headers = rawHeaders.map(normalizeHeader);
  const records = [];
  for (const line of lines.slice(1)) {
    const cols = parseCsvLine(line);
    const row = {};
    for (let i = 0; i < headers.length; i += 1) {
      row[headers[i]] = cols[i] ?? "";
    }
    records.push(row);
  }
  return records;
}

function parseZoneTab(text) {
  const map = new Map();
  const lines = text.split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const parts = trimmed.split(/\t+/);
    if (parts.length < 3) continue;
    const countries = parts[0].split(",").map((c) => c.trim()).filter(Boolean);
    const tz = parts[2].trim();
    for (const cc of countries) {
      if (!map.has(cc)) map.set(cc, new Set());
      map.get(cc).add(tz);
    }
  }
  return map;
}

function buildRows(countries, tzMap) {
  const rows = [];
  for (const row of countries) {
    const alpha2 = getField(row, ["iso3166-1-alpha-2", "iso3166-1 alpha-2", "alpha-2", "alpha 2"]);
    if (!alpha2) continue;
    const name =
      getField(row, ["official name en", "cldr display name", "country name", "name"]) ||
      alpha2;
    const alpha3 = getField(row, ["iso3166-1-alpha-3", "iso3166-1 alpha-3", "alpha-3", "alpha 3"]);
    const numeric = padNumeric(
      getField(row, ["iso3166-1-numeric", "iso3166-1 numeric", "numeric"])
    );
    const region = getField(row, ["region"]);
    const subRegion = getField(row, ["sub-region", "sub region"]);
    const intermediateRegion = getField(row, ["intermediate region"]);
    const iso3166_2 = getField(row, ["iso3166-2", "iso3166 2"]);
    const timezones = Array.from(tzMap.get(alpha2) || []);

    const attrs = {
      iso_alpha3: alpha3 || null,
      iso_numeric: numeric || null,
      iso_3166_2: iso3166_2 || null,
      region: region || null,
      sub_region: subRegion || null,
      intermediate_region: intermediateRegion || null,
      timezones,
    };

    rows.push({
      code: alpha2,
      name,
      iso_country_code: alpha2,
      iso_numeric_code: numeric || null,
      attrs,
    });
  }
  return rows;
}

function renderSql(rows) {
  const header = `-- Auto-generated by tools/build_jurisdiction_seed.mjs\n-- Sources:\n--  ${SOURCES.countries}\n--  ${SOURCES.timezones}\n\nBEGIN;\n`;
  const footer = "\nCOMMIT;\n";

  const chunks = chunkArray(rows, 200);
  const statements = chunks.map((chunk) => {
    const values = chunk
      .map((row) => {
        const attrs = JSON.stringify(row.attrs);
        return `  (NULL, ${sqlString(row.code)}, ${sqlString(row.name)}, 'COUNTRY', ${sqlString(
          row.iso_country_code
        )}, ${row.iso_numeric_code ? sqlString(row.iso_numeric_code) : "NULL"}, ${sqlString(
          attrs
        )}::jsonb)`;
      })
      .join(",\n");
    return `INSERT INTO eip_core.jurisdiction\n  (tenant_id, code, name, level, iso_country_code, iso_numeric_code, attrs)\nVALUES\n${values}\nON CONFLICT DO NOTHING;\n`;
  });

  return header + statements.join("\n") + footer;
}

async function main() {
  const [countriesText, zonesText] = await Promise.all([
    fetchText(SOURCES.countries),
    fetchText(SOURCES.timezones),
  ]);

  const countries = parseCountryCsv(countriesText);
  const tzMap = parseZoneTab(zonesText);
  const rows = buildRows(countries, tzMap).sort((a, b) => a.code.localeCompare(b.code));

  if (!rows.length) {
    throw new Error("No jurisdictions generated. Check source data.");
  }

  const sql = renderSql(rows);
  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, sql, "utf8");

  console.log(`Wrote ${rows.length} jurisdictions to ${OUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
